### ISSUE TITLE
Test Selectors with Pseudo Class

### ISSUE THREAD

**Issue by ChristianMurphy** [ChristianMurphy/postcss-combine-duplicated-selectors#15]
E.G.
``` css
a:link {
    color: #FF0000;
}
```
