### ISSUE TITLE
Test Selectors with Pseudo Elements

### ISSUE THREAD

**Issue by ChristianMurphy** [ChristianMurphy/postcss-combine-duplicated-selectors#16]
E.G.
``` css
p::first-line {
    color: #ff0000;
    font-variant: small-caps;
}
```
