### ISSUE TITLE
Handle nested @ selectors

### ISSUE THREAD

**Issue by ChristianMurphy** [ChristianMurphy/postcss-combine-duplicated-selectors#212]
E.G.

```css
@media screen {
  @supports (display: grid) {
    div {
      display: grid;
    }
  }
}
```
