### ISSUE TITLE
Handle media queries

### ISSUE THREAD

**Issue by ChristianMurphy** [ChristianMurphy/postcss-combine-duplicated-selectors#6]
currently css like:

``` css
.module {
  color: green
}
.another-module {
  color: blue
}
@media (max-width: 600px) {
  .module {
    background: red
  }
  .another-module {
    background: yellow
  }
}
```

outputs

``` css
.module {
  color: green;
  background: red
}
.another-module {
  color: blue;
  background: yellow
}
@media (max-width: 600px) {
}
```

When media selectors usually mean that the two should not be combined

expected result would be

``` css
.module {
  color: green
}
.another-module {
  color: blue
}
@media (max-width: 600px) {
  .module {
    background: red
  }
  .another-module {
    background: yellow
  }
}
```
