### ISSUE TITLE
Delete duplicate porperties

### ISSUE THREAD

**Issue by aldebaran798** [ChristianMurphy/postcss-combine-duplicated-selectors#76]
When combine it selectors is common get things like this.

.myClass {
  background: red;
  font-size: 15px;
  color: black;
  background: green;
}

The cascade takes de second background property, ¿is possible delete the first one?.

Thank you!

**Comment by ChristianMurphy** [comment]
Hi @aldebaran798! 👋 
That is a good idea, but a bit more challenging than it at first appears.

In your example
```css
.myClass {
  background: red;
  background: green;
}

/* could be combined into */

.myClass {
  background: green;
}
```

However in this case

```css
.myClass {
  background: rgb(255, 255, 255);
  background: rgba(255, 255, 255, 0.5);
}

/* should not be combined, because the first rule is a fallback if the second rule fails */
```

Meaning there are three options:
1. Make all rules unique, and occasionally break the stylesheet.
2. Leave those duplicates as is, and leave some cruft behind.
3. Attempt to determine when a duplicate is being used as a fallback.

Option 3 sounds like it would require maintaining a known fallback list, which could take a lot of time to create maintain.
So I would lean towards adding a flag that would allow switching between option 1 and 2.

What are your thoughts? 💭 
Would you be interested in opening a pull request to add the functionality?
