### ISSUE TITLE
Broken identical `@keyframes`

### ISSUE THREAD

**Issue by cuongvuong-phoenix** [ChristianMurphy/postcss-combine-duplicated-selectors#834]
## Description
When defining multiple identical `@keyframes`, all definitions except the first one are empty.

## Reproduction

- Input file:
  ```css
  @keyframes pulse {
    50% {
      opacity: 0.5;
    }
  }
  
  @keyframes pulse {
    50% {
      opacity: 0.5;
    }
  }
  ```

- Output file:
  ```css
  @keyframes pulse {
    50% {
      opacity: 0.5;
    }
  }
  
  @keyframes pulse {
  }
  ```

## Environment
- **`postcss`:** `8.4.7`
- **`postcss-combine-duplicated-selectors`:** `10.0.3`
